monitor_names: [ 'publisher.name','subscriber01.name' ]
metrics:
  goCollector: true
  processStatus: true
  callsActive: true
  callsInProgress: true
  callsCompleted: true
  partiallyRegisteredPhone: true
  registeredHardwarePhones: true
  gatewaysSessionsActive: true
  gatewaysSessionsFailed: true
  phoneSessionsActive: true
  phoneSessionsFailed: true
  callsAttempted: false
  gatewayRegistrationFailures: false
  gatewaysInService: false
  gatewaysOutOfService: false
  annunciatorOutOfResources: false
  annunciatorResourceActive: false
  annunciatorResourceAvailable: false
  annunciatorResourceTotal: false
  authenticatedCallsActive: false
  authenticatedCallsCompleted: false
  authenticatedPartiallyRegisteredPhone: false
  authenticatedRegisteredPhones: false
  callManagerHeartBeat: false
  cumulativeAllocatedResourceCannotOpenPort: false
  encryptedCallsActive: false
  encryptedCallsCompleted: false
  encryptedPartiallyRegisteredPhones: false
  encryptedRegisteredPhones: false
  hwConferenceActive: false
  hwConferenceCompleted: false
  hwConferenceOutOfResources: false
  hwConferenceResourceActive: false
  hwConferenceResourceAvailable: false
  hwConferenceResourceTotal: false
  mtpOutOfResources: false
  mtpRequestsThrottled: false
  mtpResourceActive: false
  mtpResourceAvailable: false
  mtpResourceTotal: true
  registeredAnalogAccess: false
  registeredMGCPGateway: false
  registeredOtherStationDevices: false
  registeredBOTJabberMRA: false
  registeredBOTJabberNonMRA: false
  registeredCSFJabberMRA: false
  registeredCSFJabberNonMRA: false
  registeredTABJabberMRA: false
  registeredTABJabberNonMRA: false
  registeredTCTJabberMRA: false
  registeredTCTJabberNonMRA: false
  sipLineServerAuthorizationChallenges: false
  sipLineServerAuthorizationFailures: false
  sipTrunkApplicationAuthorizationFailures: false
  sipTrunkApplicationAuthorizations: false
  sipTrunkAuthorizationFailures: false
  sipTrunkAuthorizations: false
  sipTrunkServerAuthenticationChallenges: false
  swConferenceActive: false
  swConferenceCompleted: false
  swConferenceOutOfResources: false
  swConferenceResourceActive: false
  swConferenceResourceAvailable: false
  swConferenceResourceTotal: false
  systemCallsAttempted: false
  transcoderOutOfResources: false
  transcoderRequestsThrottled: false
  transcoderResourceActive: false
  transcoderResourceAvailable: false
  transcoderResourceTotal: false
  unEncryptedCallFailures: false
  videoCallsActive: false
  videoCallsCompleted: false
  videoOnHoldOutOfResources: false
  videoOnHoldResourceActive: false
  videoOutOfResources: false
port: 9719
apiAddress: publisher.name
apiUser: api_allowed_user
apiPwd: password
apiTimeout: 15
ignoreCertificate: true
allowStop: false
sleepBetweenRequest: 30
log:
  level: info
  fileName: ''
  jsonFormat: false
  logProgramInfo: false
  maxSize: 50
  maxBackups: 5
  maxAge: 30
  quiet: false
